
import { useMemo, useState } from 'react'
import { CalendarDays, ChevronLeft, ChevronRight, CircleHelp, Clock3, FileUp, Heart, Info, Leaf, Menu, Plus, Settings, ShoppingBasket, Sparkles, Star, X } from 'lucide-react'

type Recipe = { name: string; category: string; time: string; cost: number; color: string; ingredients: string[]; rating: number }

const recipes: Recipe[] = [
  { name: 'Bowl mediterráneo', category: 'Fresco y ligero', time: '25 min', cost: 8.4, color: 'mint', rating: 5, ingredients: ['Quinoa · 120 g', 'Tomate cherry · 180 g', 'Pepino · 1 unidad', 'Hummus · 80 g'] },
  { name: 'Tacos de pollo', category: 'Favorito familiar', time: '30 min', cost: 9.8, color: 'peach', rating: 5, ingredients: ['Tortillas · 6 unidades', 'Pechuga de pollo · 300 g', 'Aguacate · 1 unidad', 'Lima · 2 unidades'] },
  { name: 'Pasta primavera', category: 'Vegetariano', time: '20 min', cost: 6.7, color: 'lavender', rating: 4, ingredients: ['Pasta integral · 250 g', 'Calabacín · 1 unidad', 'Pimiento rojo · 1 unidad', 'Parmesano · 40 g'] },
  { name: 'Lentejas caseras', category: 'De cuchara', time: '45 min', cost: 5.2, color: 'sage', rating: 5, ingredients: ['Lentejas · 250 g', 'Zanahoria · 2 unidades', 'Patata · 2 unidades', 'Pimentón · 1 cucharadita'] },
  { name: 'Salmón al horno', category: 'Rico en omega 3', time: '35 min', cost: 12.6, color: 'blue', rating: 4, ingredients: ['Salmón · 2 lomos', 'Brócoli · 300 g', 'Limón · 1 unidad', 'Ajo · 2 dientes'] },
  { name: 'Crema de calabaza', category: 'Suave y reconfortante', time: '35 min', cost: 4.9, color: 'cream', rating: 5, ingredients: ['Calabaza · 600 g', 'Cebolla · 1 unidad', 'Nata · 100 ml', 'Nuez moscada · al gusto'] },
  { name: 'Arroz tres delicias', category: 'Fácil y completo', time: '25 min', cost: 7.3, color: 'yellow', rating: 4, ingredients: ['Arroz · 250 g', 'Guisantes · 100 g', 'Huevos · 2 unidades', 'Jamón cocido · 100 g'] },
]
const weekdays = ['Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes']
const calendarStart = new Date(Date.UTC(2026, 8, 28))
const dateFormatter = new Intl.DateTimeFormat('es-ES', { day: 'numeric', month: 'long' })

export default function App() {
  const [week, setWeek] = useState(1)
  const [selected, setSelected] = useState<Recipe | null>(recipes[0])
  const [showSettings, setShowSettings] = useState(false)
  const [inflation, setInflation] = useState(3)
  const [notice, setNotice] = useState('')
  const weekRecipes = useMemo(() => Array.from({ length: 5 }, (_, i) => recipes[(week - 1) * 5 + i] ?? recipes[(i + week * 2) % recipes.length]), [week])
  const weekDates = useMemo(() => Array.from({ length: 5 }, (_, i) => {
    const date = new Date(calendarStart)
    date.setUTCDate(calendarStart.getUTCDate() + (week - 1) * 7 + i)
    return date
  }), [week])
  const monthly = weekRecipes.reduce((sum, recipe) => sum + recipe.cost * (1 + inflation / 100), 0)

  function showNotice(text: string) { setNotice(text); window.setTimeout(() => setNotice(''), 2600) }

  return <main className="min-h-screen bg-[#f8faf8] text-[#17251f]">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-10">
      <div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-2xl bg-[#183c32] text-white shadow-sm"><Leaf /></div><div><p className="text-lg font-bold tracking-tight">SmartMenu</p><p className="text-xs text-[#75837c]">Tu semana, más sencilla</p></div></div>
      <nav className="hidden items-center gap-7 text-sm font-medium text-[#68766f] md:flex"><button className="text-[#183c32]">Mi menú</button><button onClick={() => setShowSettings(true)} className="flex items-center gap-2 hover:text-[#183c32]"><Settings size={16}/> Ajustes</button><button className="flex items-center gap-2 hover:text-[#183c32]"><CircleHelp size={16}/> Ayuda</button></nav>
      <button aria-label="Abrir menú" onClick={() => setShowSettings(true)} className="rounded-xl p-2 md:hidden"><Menu /></button>
    </header>

    <section className="mx-auto max-w-7xl px-5 pb-10 pt-4 lg:px-10 lg:pt-12">
      <div className="mb-8 flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><div><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-[#e6f3ed] px-3 py-1.5 text-xs font-semibold text-[#32725b]"><Sparkles size={14}/> Plan inteligente</div><h1 className="text-3xl font-bold tracking-[-0.04em] sm:text-5xl">Menú de primavera</h1><p className="mt-3 max-w-lg text-sm leading-6 text-[#74817b]">Cinco semanas de comidas variadas, equilibradas y pensadas para disfrutar en familia.</p></div><button onClick={() => showNotice('¡Lista de compra preparada!')} className="flex items-center justify-center gap-2 rounded-2xl bg-[#27356f] px-5 py-3 text-sm font-semibold text-white shadow-lg shadow-[#27356f]/15 transition hover:bg-[#1d2857]"><ShoppingBasket size={18}/> Ver lista de compra</button></div>
      <div className="mb-8 flex items-center gap-2 overflow-x-auto pb-1">{[1,2,3,4,5].map(n => <button key={n} onClick={() => {setWeek(n);setSelected(null)}} className={`whitespace-nowrap rounded-xl px-5 py-3 text-sm font-semibold transition ${week === n ? 'bg-[#27356f] text-white shadow-md shadow-[#27356f]/15' : 'bg-white text-[#809088] ring-1 ring-[#e2e9e4] hover:text-[#27356f]'}`}>Semana {n}</button>)}</div>
      <div className="mb-5 flex items-center justify-between"><div><h2 className="text-xl font-bold">Semana {week}</h2><p className="mt-1 text-sm text-[#819089]">Del {dateFormatter.format(weekDates[0])} al {dateFormatter.format(weekDates[4])}</p></div><div className="flex gap-2"><button className="grid size-9 place-items-center rounded-xl bg-white text-[#738078] ring-1 ring-[#e2e9e4]" onClick={() => setWeek(Math.max(1, week-1))}><ChevronLeft size={18}/></button><button className="grid size-9 place-items-center rounded-xl bg-white text-[#738078] ring-1 ring-[#e2e9e4]" onClick={() => setWeek(Math.min(5, week+1))}><ChevronRight size={18}/></button></div></div>
      <div className="grid gap-4 md:grid-cols-5">{weekdays.map((day, index) => { const recipe = weekRecipes[index]; const dayStyles = ['bg-[#e6f3ed] text-[#32725b] ring-[#b9dfca]', 'bg-[#fff0e9] text-[#a96d58] ring-[#f2cbbb]', 'bg-[#f0edfa] text-[#7569a0] ring-[#d3ccef]', 'bg-[#eaf2fb] text-[#52749b] ring-[#c5dbee]', 'bg-[#fff5dc] text-[#9b7841] ring-[#ead59d]']; return <button key={day} onClick={() => setSelected(recipe)} className="group text-left"><div className="mb-2 flex items-center justify-between px-1"><span className={`rounded-lg px-2.5 py-1 text-[11px] font-bold uppercase tracking-wider ring-1 ${dayStyles[index]}`}>{day}</span><span className="rounded-md bg-white px-1.5 py-0.5 text-xs font-medium text-[#809088] ring-1 ring-[#e2e9e4]">{String(weekDates[index].getUTCDate()).padStart(2, '0')}</span></div><div className={`recipe-card ${recipe.color} relative flex min-h-[230px] flex-col justify-between overflow-hidden rounded-3xl p-5 transition duration-300 group-hover:-translate-y-1 group-hover:shadow-lg`}><div><span className="rounded-full bg-white/70 px-2.5 py-1 text-[10px] font-bold text-[#486258]">{recipe.category}</span><h3 className="mt-14 text-xl font-bold leading-tight text-[#21352c]">{recipe.name}</h3></div><div className="flex items-center justify-between text-xs font-medium text-[#60766b]"><span className="flex items-center gap-1"><Clock3 size={14}/>{recipe.time}</span><span className="font-bold">{(recipe.cost * (1 + inflation/100)).toFixed(2)} €</span></div><div className="recipe-orb" aria-hidden="true"/></div></button> })}</div>
      <div className="mt-6 grid gap-4 sm:grid-cols-3"><div className="rounded-3xl bg-[#e9f4ee] p-5"><p className="text-xs font-semibold text-[#56806c]">Coste estimado semanal</p><p className="mt-2 text-2xl font-bold text-[#183c32]">{monthly.toFixed(2)} €</p><p className="mt-1 text-xs text-[#739181]">Actualizado con +{inflation}% de inflación</p></div><div className="rounded-3xl bg-[#fff0e9] p-5"><p className="text-xs font-semibold text-[#a96d58]">Variedad en tu mesa</p><p className="mt-2 text-2xl font-bold text-[#713f31]">5 / 5</p><p className="mt-1 text-xs text-[#a77c6d]">Platos únicos esta semana</p></div><div className="rounded-3xl bg-[#f0edfa] p-5"><p className="text-xs font-semibold text-[#7569a0]">Tiempo medio</p><p className="mt-2 text-2xl font-bold text-[#40376b]">30 min</p><p className="mt-1 text-xs text-[#847ca8]">Para cocinar cada día</p></div></div>
    </section>

    {selected && <div className="fixed inset-0 z-50 flex items-end justify-center bg-[#17251f]/30 p-0 backdrop-blur-sm sm:items-center sm:p-6" onClick={() => setSelected(null)}><div role="dialog" aria-modal="true" aria-label={selected.name} onClick={e => e.stopPropagation()} className="w-full max-w-lg rounded-t-[2rem] bg-white p-6 shadow-2xl sm:rounded-[2rem] sm:p-8"><div className={`relative mb-6 h-36 overflow-hidden rounded-3xl recipe-card ${selected.color}`}><div className="recipe-orb"/><button aria-label="Cerrar" onClick={() => setSelected(null)} className="absolute right-3 top-3 grid size-9 place-items-center rounded-full bg-white/70"><X size={18}/></button></div><div className="flex items-start justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#56806c]">{selected.category}</p><h2 className="mt-1 text-2xl font-bold">{selected.name}</h2></div><div className="flex gap-0.5 pt-1 text-[#e9a84a]">{[1,2,3,4,5].map(n => <Star key={n} size={16} fill={n <= selected.rating ? 'currentColor' : 'none'}/>)}</div></div><div className="my-6 flex items-center justify-between border-y border-[#edf1ee] py-4 text-sm"><span className="flex items-center gap-2 text-[#74817b]"><Clock3 size={16}/>{selected.time}</span><span className="font-bold text-[#183c32]">{(selected.cost * (1 + inflation/100)).toFixed(2)} € aprox.</span></div><h3 className="mb-3 text-sm font-bold">Ingredientes para 2 personas</h3><ul className="grid grid-cols-2 gap-3 text-sm text-[#607168]">{selected.ingredients.map(item => <li key={item} className="flex items-center gap-2"><span className="size-1.5 rounded-full bg-[#53a17d]"/>{item}</li>)}</ul><button onClick={() => showNotice('Plato añadido a favoritos')} className="mt-7 flex w-full items-center justify-center gap-2 rounded-2xl bg-[#183c32] py-3.5 text-sm font-semibold text-white"><Heart size={17}/> Guardar en favoritos</button></div></div>}
    {showSettings && <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#17251f]/30 p-5 backdrop-blur-sm" onClick={() => setShowSettings(false)}><div onClick={e => e.stopPropagation()} className="w-full max-w-md rounded-[2rem] bg-white p-7 shadow-2xl"><div className="flex items-center justify-between"><div><p className="text-xs font-bold uppercase tracking-wider text-[#56806c]">Configuración</p><h2 className="mt-1 text-2xl font-bold">Ajustes de costes</h2></div><button aria-label="Cerrar ajustes" onClick={() => setShowSettings(false)} className="grid size-9 place-items-center rounded-full bg-[#f1f5f2]"><X size={18}/></button></div><div className="mt-7 rounded-2xl bg-[#f5f8f5] p-4"><div className="flex items-center justify-between"><label htmlFor="inflation" className="text-sm font-semibold">Inflación aplicada</label><span className="rounded-lg bg-white px-2.5 py-1 text-sm font-bold text-[#1c7358]">{inflation}%</span></div><input id="inflation" type="range" min="0" max="15" value={inflation} onChange={e => setInflation(Number(e.target.value))} className="mt-5 w-full accent-[#1c7358]"/><div className="mt-2 flex justify-between text-[11px] text-[#87958d]"><span>Sin inflación</span><span>15% máximo</span></div></div><div className="mt-4 rounded-2xl border border-dashed border-[#cddbd2] p-5 text-center"><FileUp className="mx-auto text-[#4d9a78]"/><p className="mt-2 text-sm font-semibold">Actualizar banco de ingredientes</p><p className="mt-1 text-xs text-[#819089]">Importa un CSV o JSON con tus precios</p><label className="mt-4 inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#e6f3ed] px-4 py-2.5 text-xs font-bold text-[#32725b]"><Plus size={15}/> Elegir archivo<input type="file" accept=".csv,.json" className="sr-only" onChange={() => showNotice('Archivo listo para importar')}/></label></div><div className="mt-5 flex gap-2 rounded-xl bg-[#fff7ed] p-3 text-xs leading-5 text-[#947557]"><Info size={16} className="shrink-0"/> Los precios se recalculan automáticamente en todo tu menú.</div></div></div>}
    {notice && <div role="status" className="fixed bottom-5 left-1/2 z-[60] -translate-x-1/2 rounded-2xl bg-[#183c32] px-5 py-3 text-sm font-semibold text-white shadow-xl">{notice}</div>}
  </main>
}


